<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKvt58jt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKvt58jt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKvt58jt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKvt58jt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKvt58jt\appProdProjectContainer([
    'container.build_hash' => 'Kvt58jt',
    'container.build_id' => '3693b258',
    'container.build_time' => 1592134188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKvt58jt');
